### ISSUE TITLE
more gitignores

### ISSUE THREAD

**Issue by nsheff** [databio/DESeq-Packager#1]
you should clean out files like these from your git repository:

https://github.com/databio/DESeq-Packager/blob/master/expr_tsv/.Rhistory
https://github.com/databio/DESeq-Packager/blob/master/expr_tsv/.DS_Store

add these to gitignore. and remove from the repo.

here are some more gitignore ideas:

https://github.com/databio/newproject/blob/master/.gitignore

**Comment by aaron-gu** [comment]
I fixed these a while ago but forgot to close the issue.
