### ISSUE TITLE
don't install packages from a function

### ISSUE THREAD

**Issue by nsheff** [databio/DESeq-Packager#2]
using `requireNamespace()` is great -- but if a required package doesn't exist, it's not good manners to just force the user to install it... it's better to just provide an error message and ask the user to install it.

just put a list of required prereqs in the readme and then throw an error if they aren't installed in your fucntion.

**Comment by aaron-gu** [comment]
Should the message be an `error()` or just let R throw its own error?

**Comment by nsheff** [comment]
it depends on what you want to do. if you use `error()` it will stop processing, if you use `message` it will not.

**Comment by nsheff** [comment]
in this case, if the prereqs don't exist, you can cause a break.
