### ISSUE TITLE
repo cleanup

### ISSUE THREAD

**Issue by nsheff** [databio/DESeq-Packager#4]
- [x] remove dot files in `expr_tsv`. make sure these are `.gitignore`d
- [x] raw data should not be version controlled in a git repository. move it to `big.databio.org` as a download
- [x] R tutorials should be written as `Rmarkdown` vignettes generally. the `test_pckgr.R` script should become a compilable Rmarkdown file.
- [x] example peps should live in the `example_pep` repository
- [x] quick start should contain actual code that can be copy/pasted and run, rather than just prose descriptions of what to do.
- [x] this file lacks an actual name and has only an extension: https://github.com/databio/DESeq-Packager/blob/dfe90e20b750e6b47b23348b9b83f6c6c38951df/test_pckgr.R#L13

**Comment by nsheff** [comment]
See also: https://github.com/databio/example-projects/tree/master/rna-seq

**Comment by aaron-gu** [comment]
raw data moved to http://big.databio.org/example_data/

**Comment by aaron-gu** [comment]
Since my pep in here is specific to the `expr_tsv` data, should I just keep it here or add the data to the `pepkit/example_peps/data` folder and create a new folder for the `project_config.yaml` and `sample_annotation.csv`?
